#+TITLE: Emacs Config
#+Author: Filip Lindahl

* Customize settings
  A custom file to keep customizations out of
  [[file:init.el][init.el]]. All to declutter my [[file:init.el][init.el]].
  #+begin_src emacs_lisp
  (setq custom-file (expand-file-name "custom.el" user-emacs-directory))
  (load custom-file)
  #+end_src

  Loading contents from a file containing all of my life ruining secrets.
  #+begin_src emacs-lisp
  (if (file-exists-p "private.el") (load-file (concat user-emacs-directory "private.el")))
  #+end_src

  Diminish mode, for less clutter.
  #+begin_src emacs-lisp
  (use-package diminish
  :ensure t)
  #+end_src
* Themes
** Adwaita
Lighter theme for lighter days.
   #+begin_src emacs-lisp
  (load-theme 'adwaita t)
   #+end_src
* Font
  [[https://fonts.google.com/specimen/Inconsolata][Inconsolata]] is a pleasant  monospaced font.
  You can install it on Arch-Linux using packer, which would look like this:

  #+begin_src sh
  packer -S ttf-inconsolata
  #+end_src
  And to tell Emacs to use that font you add:
  #+begin_src emacs-lisp
  (add-to-list 'default-frame-alist
  '(font . "Inconsolata-14"))
  #+end_src
* Sane defaults
  #+begin_src emacs-lisp
  ;; Less prompting
  (fset 'yes-or-no-p 'y-or-n-p)

  ;; Put all backup in one place
  (setq backup-directory-alist '(("." . "~/.emacs.d/backups")))
  (setq auto-save-file-name-transforms '((".*" "~/.emacs.d/auto-save-list/" t)))

  ;; Delete regions when marked
  (delete-selection-mode t)

  ;; Tell me what column my marker is in.
  (column-number-mode t)

  ;; Quiet in Emacs, please
  (setq visible-bell t)

  ;; Company-mode everywhere
  (use-package company
  :ensure t
  :config
  (global-company-mode)
  (diminish 'company-mode))

  ;; Please no bars.
  (menu-bar-mode -1)
  (tool-bar-mode -1)
  (scroll-bar-mode -1)

  ;; Where am I on the line?
  (column-number-mode 1)

  ;; Show matching parentheses
  (show-paren-mode)
  #+end_src

  This is good for performance. Apparently.
  #+begin_src emacs-lisp
  (setq auto-window-vscroll nil)
  #+end_src
* Keybindings
  Stolen from [[https://github.com/Jassob/.emacs.d][Jassobs Emacs config]].
  Great if you don't want to memorize thousands of combinations of keys.
  #+begin_src emacs-lisp
  (use-package guide-key
  :ensure t
  :diminish guide-key-mode
  :config
  (setq guide-key/guide-key-sequence t
	     guide-key/popup-window-position 'bottom
	     guide-key/highlight-command-regexp ".*")
  (guide-key-mode t))
  #+end_src

  This is where I'll keep my different keybindings for all kinds of
  things.
  #+begin_src emacs-lisp
  (global-set-key (kbd "M-n w") 'make-frame-command)
  #+end_src
* Buffers
  Use ibuffer instead of list-buffers
  #+begin_src emacs-lisp
  (defalias 'list-buffers 'ibuffer)
  #+end_src

  Refresh dired in the background as well, BUT DON'T TELL ME!
  #+begin_src emacs-lisp
  (setq global-auto-revert-non-file-buffers t)
  (setq auto-revert-verbose nil)
  #+end_src

  Swap-buffers is a package that makes it easier to swap around buffers to get the placements you want.
  #+begin_src emacs-lisp
  (use-package swap-buffers
   :ensure t
   :bind
    ("M-s M-s" . swap-buffers))
  #+end_src
* Recent files
  Binding helms recentf to have recent files more easily accessible.
  #+begin_src emacs-lisp
  (use-package recentf
   :bind ("C-c C-r" . helm-recentf)
   :config
   (recentf-mode t)
   (setq recentf-max-saved-items 25))
  #+end_src
* Org-mode
  Visual lines in org mode for better readability.
  #+begin_src emacs-lisp
  (add-hook 'org-mode-hook 'visual-line-mode)
  #+end_src

  Indent those headers for me please.
  #+begin_src emacs-lisp
  (add-hook 'org-mode-hook 'org-indent-mode)
  #+end_src

* Helm
  helm-M-x is a beautiful thing that always helps me find what command
  I need.
  #+begin_src emacs-lisp
  (use-package helm
  :ensure t
  :bind
   (("M-x" . helm-M-x)))
   #+end_src
* Ido
  Looking for things using Ido is a more efficient way of looking
  while still keeping that "Emacs-way" of life.
  #+begin_src emacs-lisp
  (use-package ido
  :ensure t
  :config
  (ido-mode))
  #+end_src
* Magit
  Magit is a great interface for git. Much smoother than using command
  line git.
  #+begin_src emacs-lisp
  (use-package magit
  :ensure t
  :defer t
  :bind ("C-c g" . magit-status)
  :config
   (define-key magit-status-mode-map (kbd "q") 'magit-quit-session))
  #+end_src

  Not using it right now, but will leave it here for people that might be interested.
  # MagitHub
  # #+begin_src emacs-lisp
  # (use-package magithub
  # :ensure t
  # :defer t
  # :after magit
  # :config (magithub-feature-autoinject t))
  # #+end_src

* Programming
** General
   Line numbering.
   #+begin_src emacs-lisp
   (add-hook 'prog-mode-hook 'linum-mode)
   #+end_src

   Rainbow delimiters in all languages!
   #+begin_src emacs-lisp
   (use-package rainbow-delimiters
   :ensure t
   :config
   (add-hook 'prog-mode-hook 'rainbow-delimiters-mode))
   #+end_src

   Remove trailing whitespace when saving files.
   #+begin_src emacs-lisp
   (add-hook 'before-save-hook 'delete-trailing-whitespace)
   #+end_src

   Comment/uncomment regions of code.
   #+begin_src emacs-lisp
   (global-set-key (kbd "C-x c") 'comment-or-uncomment-region)
   #+end_src

   Multimarkers!
   #+begin_src emacs-lisp
   (use-package multiple-cursors
   :ensure t
   :bind
   (("C-s-c C-s-c" . mc/edit-lines)
   ("C-s->" . mc/mark-next-like-this)
   ("C-s-<" . mc/mark-previous-like-this)
   ("C-s-h" . mc/mark-all-like-this)))
   #+end_src

** Python
   Some Python packages needed for a working Elpy env. should be
   installed before elpy is installed and configured.
   #+begin_src sh
   # Either of these
   pip install rope
   pip install jedi
   # flake8 for code checks
   pip install flake8
   # importmagic for automatic imports
   pip install importmagic
   # and autopep8 for automatic PEP8 formatting
   pip install autopep8
   # and yapf for code formatting
   pip install yapf
   #+end_src
   Or you could the the whole install with a oneliner
   #+begin_src sh
   pip install jedi flake8 importmagic autopep8
   #+end_src
   Enables Elpy, a nice Python environment.
   #+begin_src emacs-lisp
   (use-package elpy
   :ensure t
   :config
    (add-hook 'python-mode-hook 'elpy-enable))
   #+end_src
** C++

Parse header files with C++ parsing.
#+begin_src emacs-lisp
(add-to-list 'auto-mode-alist '("\\.h\\'" . c++-mode))
#+end_src

Irony mode
#+begin_src emacs-lisp
(use-package irony
:ensure t
  :config
    (add-hook 'c++-mode-hook 'irony-mode)
    (add-hook 'c-mode-hook 'irony-mode)
    (add-hook 'objc-mode-hook 'irony-mode)
    (add-hook 'irony-mode-hook 'irony-cdb-autosetup-compile-options))
#+end_src

Company for irony mode
#+begin_src emacs-lisp
(use-package company-irony
  :ensure t
  :config
    (add-to-list 'company-backends 'company-irony))
#+end_src

Flycheck for irony
#+begin_src emacs-lisp
(use-package flycheck-irony
  :after flycheck
  :ensure t
  :config
    (add-hook 'flycheck-mode-hook #'flycheck-irony-setup))
#+end_src
*** GLSL
OpenGL Shader Language.

#+begin_src emacs-lisp
(use-package glsl-mode
  :ensure t
  :config
  (add-to-list 'auto-mode-alist '("\\.glsl\\'" . glsl-mode))
  (add-to-list 'auto-mode-alist '("\\.vert\\'" . glsl-mode))
  (add-to-list 'auto-mode-alist '("\\.frag\\'" . glsl-mode))
  (add-to-list 'auto-mode-alist '("\\.geom\\'" . glsl-mode)))
#+end_src

Company-glsl requires glslangValidator which can be found [[https://github.com/KhronosGroup/glslang][here]].
#+begin_src emacs-lisp
(use-package company-glsl
  :ensure t
  :config
  (add-to-list 'company-backends 'company-glsl))
#+end_src
** C#
#+begin_src emacs-lisp

(defun my-csharp-mode-setup ()
  (omnisharp-mode)
  (company-mode)
  (flycheck-mode)

  (setq indent-tabs-mode nil)
  (setq c-syntactic-indentation t)
  (c-set-style "ellemtel")
  (setq c-basic-offset 4)
  (setq truncate-lines t)
  (setq tab-width 4)
  (setq evil-shift-width 4)

  (electric-pair-local-mode 1)

  (local-set-key (kbd "C-c r r") 'omnisharp-run-code-action-refactoring)
  (local-set-key (kbd "C-c C-c") 'recompile))

#+end_src
#+begin_src emacs-lisp
(use-package csharp-mode
:ensure t
)

(use-package omnisharp
:ensure t
:config
(add-hook 'csharp-mode-hook 'my-csharp-mode-setup t)
(add-to-list 'company-backends 'company-omnisharp))
#+end_src
** Erlang
EDTS - Erlang Development Tool Suite
#+begin_src emacs-lisp
(use-package edts
:ensure t
:init
(require 'edts-start))
#+end_src
** Java
#+begin_src emacs-lisp
(use-package meghanada
:ensure t
:bind
(:map meghanada-mode-map
(("C-M-o" . meghanada-optimize-import)
("C-M-t" . meghanada-import-all)))
:config
(add-hook 'java-mode-hook 'tkj-java-meghanda-mode-hook))

(defun tkj-java-meghanda-mode-hook ()
(meghanada-mode)
(flycheck-mode))
#+end_src
* Web Development
** Server
  Impatient mode, showing changes made to your page immediately.
  Access at localhost:8080/imp
  #+begin_src emacs-lisp
  (use-package impatient-mode
  :ensure t
  :config
  (add-hook 'web-mode-hook 'impatient-mode))
  #+end_src

  Simple-httpd, needed for impatient-mode.
  Also starts browser on page.
  #+begin_src emacs-lisp
  (use-package simple-httpd
  :ensure t)
  #+end_src

** HTML
  #+begin_src emacs-lisp
  (use-package web-mode
  :ensure t
  :config
  (add-to-list 'auto-mode-alist '("\\.html?\\'" . web-mode)))
  #+end_src

** CSS
** JavaScript
  js2-mode for Js
  #+begin_src emacs-lisp
  (use-package js2-mode
  :ensure t
  :config
  (add-to-list 'auto-mode-alist '("\\.js?\\'" . js2-mode)))
  #+end_src

#+begin_src emacs-lisp
(add-to-list 'auto-mode-alist '("\\.jsx\\'" . web-mode))
(add-hook 'web-mode-hook
          (lambda ()
            (when (string-equal "jsx" (file-name-extension buffer-file-name))
              (setup-tide-mode))))
;; enable typescript-tslint checker
;;(flycheck-add-mode 'typescript-tslint 'web-mode)
#+end_src


** TypeScript
TIDE - TypeScript Interactive Development Environment

#+begin_src emacs-lisp
(use-package tide
:ensure t
:config
(setq company-tooltip-align-annotations t)
(add-hook 'before-save-hook 'tide-format-before-save)
(add-hook 'typescript-mode-hook #'setup-tide-mode))
#+end_src

#+begin_src emacs-lisp
(defun setup-tide-mode ()
(interactive)
(tide-setup)
(flycheck-mode +1)
(setq flycheck-check-syntax-automatically '(save-mode-enabled))
(eldoc-mode +1)
(tide-hl-identifier-mode +1)
(company-mode +1))
#+end_src

#+begin_src emacs-lisp
(add-to-list 'auto-mode-alist '("\\.tsx\\'" . web-mode))
(add-hook 'web-mode-hook
          (lambda ()
            (when (string-equal "tsx" (file-name-extension buffer-file-name))
              (setup-tide-mode))))
;; enable typescript-tslint checker
(flycheck-add-mode 'typescript-tslint 'web-mode)
#+end_src

* LaTeX
#+begin_src emacs-lisp
(use-package auctex
:defer t
:ensure t
:config
((setq TeX-auto-save t)
 (setq TeX-parse-self t)
 (setq-default TeX-master nil))
 (add-hook 'LaTeX-mode-hook 'visual-line-mode)
 (add-hook 'LaTeX-mode-hook 'flyspell-mode)
 (add-hook 'LaTeX-mode-hook 'LaTeX-math-mode)
 (add-hook 'LaTeX-mode-hook 'turn-on-reftex)
 (setq reftex-plug-into-AUCTeX t))
#+end_src
* Spotify Bindings
  Keybindings so that I can control Spotify without switching focus from Emacs.
  #+begin_src emacs-lisp
  (use-package spotify
  :ensure t
  :bind (("M-s M-n" . spotify-next)
         ("M-s M-p" . spotify-previous)
         ("M-p" . spotify-playpause)
	 ("M-s M-c" . spotify-current)
	 ("<XF86AudioPlay>" . spotify-play)))
  #+end_src
* TRAMP/Sudo
  I borrowed this from somewhere. It makes sudo access much smoother.
  #+begin_src emacs-lisp
  (defvar find-file-root-prefix (if (featurep 'xemacs) "/[sudo/root@localhost]" "/sudo:root@localhost:" )
  "*The filename prefix used to open a file with `find-file-root'.")

(defvar find-file-root-history nil
  "History list for files found using `find-file-root'.")

(defvar find-file-root-hook nil
  "Normal hook for functions to run after finding a \"root\" file.")

(defun find-file-root ()
  "*Open a file as the root user.
   Prepends `find-file-root-prefix' to the selected file name so that it
   maybe accessed via the corresponding tramp method."

  (interactive)
  (require 'tramp)
  (let* ( ;; We bind the variable `file-name-history' locally so we can
	 ;; use a separate history list for "root" files.
	 (file-name-history find-file-root-history)
	 (name (or buffer-file-name default-directory))
	 (tramp (and (tramp-tramp-file-p name)
		     (tramp-dissect-file-name name)))
	 path dir file)

    ;; If called from a "root" file, we need to fix up the path.
    (when tramp
      (setq path (tramp-file-name-localname tramp)
	    dir (file-name-directory path)))

    (when (setq file (read-file-name "Find file (UID = 0): " dir path))
      (find-file (concat find-file-root-prefix file))
      ;; If this all succeeded save our new history list.
      (setq find-file-root-history file-name-history)
      ;; allow some user customization
      (run-hooks 'find-file-root-hook))))

(global-set-key [(control x) (control r)] 'find-file-root)
  #+end_src
