(deftheme doom-molokai-fixed
  "Created 2020-02-07.")

(custom-theme-set-faces
 'doom-molokai-fixed
 '(cursor ((t (:background "#fb2874"))))
 '(fixed-pitch ((t (:family "Monospace"))))
 '(variable-pitch ((((type w32)) (:foundry "outline" :family "Arial")) (t (:family "Sans Serif"))))
 '(escape-glyph ((((background dark)) (:foreground "cyan")) (((type pc)) (:foreground "magenta")) (t (:foreground "brown"))))
 '(homoglyph ((((background dark)) (:foreground "cyan")) (((type pc)) (:foreground "magenta")) (t (:foreground "brown"))))
 '(minibuffer-prompt ((t (:foreground "#fd971f"))))
 '(highlight ((t (:foreground "#1B2229" :background "#fd971f"))))
 '(region ((t (:background "#4e4e4e"))))
 '(shadow ((t (:foreground "#555556"))))
 '(secondary-selection ((t (:background "#525254"))))
 '(trailing-whitespace ((t (:background "#e74c3c"))))
 '(font-lock-builtin-face ((t (:foreground "#fd971f"))))
 '(font-lock-comment-delimiter-face ((default (:inherit (font-lock-comment-face)))))
 '(font-lock-comment-face ((t (:foreground "#555556" :slant italic))))
 '(font-lock-constant-face ((t (:foreground "#fd971f"))))
 '(font-lock-doc-face ((t (:foreground "#7f7f80" :inherit (font-lock-comment-face)))))
 '(font-lock-function-name-face ((t (:foreground "#b6e63e" :slant normal :weight bold))))
 '(font-lock-keyword-face ((t (:foreground "#fb2874" :slant italic))))
 '(font-lock-negation-char-face ((t (:foreground "#9c91e4" :inherit (bold)))))
 '(font-lock-preprocessor-face ((t (:foreground "#9c91e4" :inherit (bold)))))
 '(font-lock-regexp-grouping-backslash ((t (:foreground "#9c91e4" :inherit (bold)))))
 '(font-lock-regexp-grouping-construct ((t (:foreground "#9c91e4" :inherit (bold)))))
 '(font-lock-string-face ((t (:foreground "#e2c770"))))
 '(font-lock-type-face ((t (:foreground "#66d9ef"))))
 '(font-lock-variable-name-face ((t (:foreground "#fd971f"))))
 '(font-lock-warning-face ((t (:inherit (warning)))))
 '(button ((t (:inherit (link)))))
 '(link ((t (:weight bold :underline (:color foreground-color :style line) :foreground "#fd971f"))))
 '(link-visited ((default (:inherit (link))) (((class color) (background light)) (:foreground "magenta4")) (((class color) (background dark)) (:foreground "violet"))))
 '(fringe ((t (:foreground "#4e4e4e" :inherit (default)))))
 '(header-line ((t (:inherit (mode-line)))))
 '(tooltip ((t (:foreground "#d6d6d4" :background "#2d2e2e"))))
 '(mode-line ((t (:box nil :background "#2d2e2e"))))
 '(mode-line-buffer-id ((t (:weight bold))))
 '(mode-line-emphasis ((t (:foreground "#fd971f"))))
 '(mode-line-highlight ((t (:inherit (highlight)))))
 '(mode-line-inactive ((t (:box nil :foreground "#4e4e4e" :background "#171819"))))
 '(isearch ((t (:foreground "#1B2229" :background "#b6e63e"))))
 '(isearch-fail ((t (:weight bold :foreground "#1B2229" :background "#e74c3c"))))
 '(lazy-highlight ((t (:weight bold :foreground "#1B2229" :background "#9c91e4"))))
 '(match ((t (:weight bold :foreground "#b6e63e" :background "#1B2229"))))
 '(next-error ((t (:inherit (region)))))
 '(query-replace ((t (:inherit (isearch)))))
 '(line-number-current-line ((t (:inherit line-number :background "light gray" :foreground "black"))))
 '(default ((t (:family "Fantasque Sans Mono" :foundry "nil" :width normal :height 181 :weight normal :slant normal :underline nil :overline nil :strike-through nil :box nil :inverse-video nil :foreground "#d6d6d4" :background "#1c1e1f" :stipple nil :inherit nil))))
 '(company-tooltip ((t (:background "gray30" :foreground "white smoke"))))
 '(company-tooltip-selection ((t (:background "black"))))
 '(company-scrollbar-bg ((t (:background "gray50"))))
 '(company-scrollbar-fg ((t (:background "gainsboro"))))
 '(company-tooltip-annotation ((t (:foreground "white smoke"))))
 '(company-tooltip-annotation-selection ((t (:inherit company-tooltip-annotation)))))

(provide-theme 'doom-molokai-fixed)
